id: D4006421C
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-01-11T09:49:07+00:00'
last_modified: '2022-05-29T07:59:51.783068+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    b4d5:
      image_group_id: I1PD95914
      title: དམ་པའི་ཆོས་པདྨ་དཀར་པོའི་འགྲེལ་པ།
      total_pages: 1538
      order: 69
      base_file: b4d5.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
