id: PF17E7DAD
initial_creation_type: ocr
source_metadata:
  volumes:
    d23343e849c24eea94d74af8ae2546bd:
      base_file: v069.txt
      image_group_id: I1PD95914
      title: དམ་པའི་ཆོས་པདྨ་དཀར་པོའི་འགྲེལ་པ།
      total_pages: 1538
      volume_number: 69
