id: PF17E7DAD
initial_creation_type: ocr
source_metadata:
  volumes:
    a4738b451c724d1c80714f1f5824b16f:
      base_file: v069.txt
      image_group_id: I1PD95914
      title: དམ་པའི་ཆོས་པདྨ་དཀར་པོའི་འགྲེལ་པ།
      total_pages: 1538
      volume_number: 69
